### ISSUE TITLE
README states end of command is '\n' but code seems to indicate '\r'

### ISSUE THREAD

**Issue by jrperrin** [FARLY7/embedded-cli#7]
https://github.com/FARLY7/embedded-cli/blob/843ee860821b87bdc33f6cdc9445a2f15d82ed19/cli_defs.h#L7

https://github.com/FARLY7/embedded-cli/blob/843ee860821b87bdc33f6cdc9445a2f15d82ed19/README.md#L80

**Comment by FARLY7** [comment]
Fixed, thanks!
