### ISSUE TITLE
`CMD_TERMINATOR` and `MAX_BUF_SIZE` should surround with #ifndef

### ISSUE THREAD

**Issue by shishirong** [FARLY7/embedded-cli#9]
let CMD_TERMINATOR can be define externally instead of  modify directly cli_defs.h

and  add a newline  to clear warning:

```log
deps\embedded-cli\cli.h(91): warning:  #1-D: last line of file ends without a newline
```

**Comment by FARLY7** [comment]
Fixed in 8d387dd836ca5b73320135d502781bf56752cf29
